// Python FSE/Deepskilling/Frontend Development/HandsOn 8/task1/components/CourseCard.vue
<template>
  <div class="card">
    <h2>{{ course.name }}</h2>

    <p>Course Code : {{ course.code }}</p>

    <p>Credits : {{ course.credits }}</p>

    <p>Grade : {{ course.grade }}</p>
  </div>
</template>

<script setup>
defineProps({
  course: Object
});
</script>

<style scoped>
.card{
    background:white;
    padding:20px;
    margin:20px 0;
    border-radius:10px;
    box-shadow:0 5px 10px rgba(0,0,0,.2);
}
</style>

// Python FSE/Deepskilling/Frontend Development/HandsOn 5/task2/CourseCard.jsx
function CourseCard({

    id,
    name,
    code,
    credits,
    grade,
    onEnroll

}){

    return(

        <div className="card">

            <h3>{name}</h3>

            <p>Course Code : {code}</p>

            <p>Credits : {credits}</p>

            <p>Grade : {grade}</p>

            <button
            onClick={()=>onEnroll(id)}
            >
                Enroll
            </button>

        </div>

    );

}

export default CourseCard;
